### ISSUE TITLE
Library not imported from github

### ISSUE THREAD

**Issue by davidlad123** [BILLyTheLiTTle/LazyColumns#7]
Using this stanza from your github article:
```
dependencies {
	 implementation 'com.github.BILLyTheLiTTle:LazyColumns:0.3.7'
}
```

Theres no update to my local libraries.. none of the classes are found. Could you please check to see theres nothing missing?

Response from gradle was:
Failed to resolve: com.github.billythelittle:LazyColumns:0.3.7

David

**Comment by BILLyTheLiTTle** [comment]
Have you used this in the project's Gradle file?
```
repositories {
	maven { url 'https://jitpack.io' }
}
```

**Comment by davidlad123** [comment]
will check

**Comment by BILLyTheLiTTle** [comment]
Since there is no feedback in this I will close it! Feel free to reopen it.
